---
  tasks:
    - name: copy lighthouse from git
      become: true
      git:
        repo: "{{ lighthouse_git }}"
        version: master
        dest: "{{ lighthouse_dir  }}"
    - name: create config
      become: true
      template:
        src: templates/lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: 0644
      notify: nginx_reload
